-- AlterTable
ALTER TABLE "system_settings"
ADD COLUMN "systemScoreMax" INTEGER NOT NULL DEFAULT 80,
ADD COLUMN "defenseScoreMax" INTEGER NOT NULL DEFAULT 20,
ADD COLUMN "logbookWeight" INTEGER NOT NULL DEFAULT 20,
ADD COLUMN "evaluationWeight" INTEGER NOT NULL DEFAULT 20,
ADD COLUMN "assessmentWeight" INTEGER NOT NULL DEFAULT 30,
ADD COLUMN "visitationWeight" INTEGER NOT NULL DEFAULT 10,
ADD COLUMN "maxVisitations" INTEGER NOT NULL DEFAULT 2;
