const mockUser = (overrides = {}) => ({
  id: "user-123",
  email: "test@example.com",
  password: "$2a$12$hashedpassword",
  firstName: "Test",
  lastName: "User",
  role: "student",
  isActive: true,
  passwordResetRequired: false,
  departmentId: "dept-123",
  facultyId: "fac-123",
  lastLogin: null,
  phone: null,
  address: null,
  bio: null,
  createdAt: new Date("2025-01-01"),
  updatedAt: new Date("2025-01-01"),
  ...overrides,
});

const mockStudent = (overrides = {}) => ({
  id: "student-123",
  userId: "user-123",
  matricNumber: "SIWES/2025/001",
  departmentId: "dept-123",
  level: 400,
  session: "2024/2025",
  cgpa: 3.5,
  hasPlacement: false,
  placementApproved: false,
  trainingCompleted: false,
  currentPlacementId: null,
  isActive: true,
  user: mockUser(),
  ...overrides,
});

const mockPlacement = (overrides = {}) => ({
  id: "placement-123",
  studentId: "student-123",
  companyName: "Tech Corp Ltd",
  companyAddress: "123 Innovation Drive",
  companyEmail: "hr@techcorp.com",
  companyPhone: "+234-800-0001",
  position: "Software Engineering Intern",
  startDate: new Date("2025-06-01"),
  endDate: new Date("2025-12-31"),
  status: "pending",
  workStartTime: "08:00",
  workEndTime: "17:00",
  acceptanceLetter: null,
  acceptanceLetterPath: null,
  createdAt: new Date("2025-01-01"),
  updatedAt: new Date("2025-01-01"),
  ...overrides,
});

const mockLogbook = (overrides = {}) => ({
  id: "logbook-123",
  studentId: "student-123",
  weekNumber: 1,
  startDate: new Date("2025-06-01"),
  endDate: new Date("2025-06-07"),
  tasksPerformed: "Completed onboarding tasks",
  skillsAcquired: "Communication, teamwork",
  challenges: "Network issues",
  lessonsLearned: "Patience is key",
  status: "submitted",
  departmentalReviewStatus: "submitted",
  industrialReviewStatus: "submitted",
  createdAt: new Date("2025-01-01"),
  updatedAt: new Date("2025-01-01"),
  ...overrides,
});

const mockAttendance = (overrides = {}) => ({
  id: "att-123",
  studentId: "student-123",
  placementId: "placement-123",
  date: new Date("2025-06-01"),
  checkInTime: new Date("2025-06-01T08:00:00"),
  checkOutTime: new Date("2025-06-01T17:00:00"),
  hoursWorked: 8,
  punctuality: "ON_TIME",
  dayStatus: "PRESENT_ON_TIME",
  approvalStatus: "PENDING",
  locationLatitude: 6.5244,
  locationLongitude: 3.3792,
  distanceFromOffice: 50.5,
  createdAt: new Date("2025-01-01"),
  updatedAt: new Date("2025-01-01"),
  ...overrides,
});

const mockAssessment = (overrides = {}) => ({
  id: "assessment-123",
  studentId: "student-123",
  supervisorId: "supervisor-123",
  placementId: "placement-123",
  type: "industrial",
  technical: 75,
  communication: 80,
  punctuality: 85,
  initiative: 70,
  teamwork: 90,
  professionalism: 80,
  problemSolving: 75,
  adaptability: 85,
  recommendation: "very_good",
  grade: "B",
  status: "completed",
  createdAt: new Date("2025-01-01"),
  updatedAt: new Date("2025-01-01"),
  ...overrides,
});

const mockFaculty = (overrides = {}) => ({
  id: "fac-123",
  name: "Engineering",
  code: "ENG",
  description: "Faculty of Engineering",
  isActive: true,
  createdAt: new Date("2025-01-01"),
  updatedAt: new Date("2025-01-01"),
  ...overrides,
});

const mockDepartment = (overrides = {}) => ({
  id: "dept-123",
  name: "Computer Engineering",
  code: "CMP",
  description: "Department of Computer Engineering",
  facultyId: "fac-123",
  isActive: true,
  createdAt: new Date("2025-01-01"),
  updatedAt: new Date("2025-01-01"),
  ...overrides,
});

const mockSupervisor = (overrides = {}) => ({
  id: "supervisor-123",
  userId: "user-456",
  type: "academic",
  departmentId: "dept-123",
  maxStudents: 10,
  isActive: true,
  isAvailable: true,
  createdAt: new Date("2025-01-01"),
  updatedAt: new Date("2025-01-01"),
  ...overrides,
});

module.exports = {
  mockUser,
  mockStudent,
  mockPlacement,
  mockLogbook,
  mockAttendance,
  mockAssessment,
  mockFaculty,
  mockDepartment,
  mockSupervisor,
};
